import Head from 'next/head'
import { MainLayout } from '@/components';
import { useContext, useEffect, useState } from 'react';
import { SocketContext } from '@/context/SocketProvider';

export default function Home() {

  const { socket, online } = useContext(SocketContext)
  const [message, setMessage] = useState<string | null>()

  useEffect(() => {
    socket?.on('hola', (payload: string) => {
      setMessage(payload)
    })
  }, [socket])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        { online ? <h1>{message}</h1> : <h1>...</h1> } 
      </MainLayout>
    </>
  )
}